### ISSUE TITLE
Concatenate sections

### ISSUE THREAD

**Issue by SammyM** [styledown/styledown#17]
Would it be possible to concatenate sections which have the same titles of the following format?:

```
/***
 * Buttons
 */
```

I have button styles in different files and I would like to add them all to the same section instead of having multiple sections with the same title in different locations within the style guide.

**Comment by nickisnoble** [comment]
If you generate your documentation from a Markdown file rather than comments, you can have them all in one section. I know it's not ideal, but that's how I did it.

On the other hand, having the docs be separate is a little better for organization, and it still of course renders the right styles

**Comment by SammyM** [comment]
Okay, thank you.
