### ISSUE TITLE
Couldn't run it on Windows

### ISSUE THREAD

**Issue by paulmelero** [styledown/styledown#23]
Even when I added it to my PATH in my _system env. variables_ (actually tested in win10) manually, it wouldn't work. I have the npm path added, also.

Only way of making it work for me was calling it with node, like:

```
'node "C:/Users/**my_user**/AppData/Roaming/npm/node_modules/styledown/bin/styledown" ./css/style.css ./scss/config.md > ./docs/index.html' 
```

Note: I had no issues on Linux. Worked just fine out-of-the-box.

**Comment by rogatty** [comment]
If you use gulp then I suggest using https://github.com/st44100/gulp-styledown which works just fine.

**Comment by paulmelero** [comment]
✔️ That made it!

❤️ Thanks, @rogatty, you saved the day! ☀️
