### ISSUE TITLE
Styledown failes to proccess css  example into html

### ISSUE THREAD

**Issue by padsbanger** [styledown/styledown#25]
Hello, 

I am trying to compile one of your examples here: https://github.com/styledown/styledown/tree/master/examples/bootstrap

After typing `make` in my terminal my `index.html` loooks like this: 

`{
  "files": {
    "buttons.css": {
      "name": "buttons.css",
      "title": null,
      "sections": {}
    },
    "forms.css": {
      "name": "forms.css",
      "title": null,
      "sections": {}
    },
    "lists.css": {
      "name": "lists.css",
      "title": null,
      "sections": {}
    },
    "panels.css": {
      "name": "panels.css",
      "title": null,
      "sections": {}
    },
    "tabs.css": {
      "name": "tabs.css",
      "title": null,
      "sections": {}
    },
    "progress.css": {
      "name": "progress.css",
      "title": null,
      "sections": {}
    },
    "components.css": {
      "name": "components.css",
      "title": null,
      "sections": {}
    },
    "_extras.css": {
      "name": "_extras.css",
      "title": "Styleguide options",
      "sections": {
        "styleguide-options": {
          "id": "styleguide-options",
          "title": "Styleguide options",
          "depth": 1,
          "parts": {
            "s1": {
              "type": "text",
              "id": "s1",
              "content": "</li>\n<li></li>\n<li>"
            }
          }
        },
        "head": {
          "id": "head",
          "title": "Head",
          "depth": 3,
          "parts": {
            "s1": {
              "type": "text",
              "id": "s1",
              "content": "</li>\n<li></li>\n<li>\n<pre><code>meta(name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;)\n</code></pre>\n</li>\n<li>\n<pre><code>link(rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')\n</code></pre>\n</li>\n<li>\n<pre><code>link(rel='stylesheet' href='_extras.css')\n</code></pre>\n</li>\n<li>\n<pre><code>link(rel='stylesheet' href='../../data/styledown.css')\n</code></pre>\n</li>\n<li>\n<pre><code>script(src='../../data/styledown.js')\n</code></pre>\n</li>\n<li></li>\n<li>"
            }
          }
        },
        "body": {
          "id": "body",
          "title": "Body",
          "depth": 3,
          "parts": {
            "s1": {
              "type": "text",
              "id": "s1",
              "content": "</li>\n<li></li>\n<li>\n<pre><code>.jumbotron.jumbotron-styleguide\n</code></pre>\n</li>\n<li>\n<pre><code>  .container\n</code></pre>\n</li>\n<li>\n<pre><code>    h1 Bootstrap styleguides\n</code></pre>\n</li>\n<li>\n<pre><code>    p\n</code></pre>\n</li>\n<li>\n<pre><code>      | This is a sample styleguide for Bootstrap that was generated using\n</code></pre>\n</li>\n<li>\n<pre><code>      | Styledown, a styleguide generator. They were taken from inline comments\n</code></pre>\n</li>\n<li>\n<pre><code>      | in the CSS.\n</code></pre>\n</li>\n<li>\n<pre><code>    p\n</code></pre>\n</li>\n<li>\n<pre><code>      a.btn.btn-default(href=&quot;https://github.com/styledown/styledown&quot;) About Styledown\n</code></pre>\n</li>\n<li>\n<pre><code>      a.btn.btn-default(href=&quot;https://github.com/styledown/styledown/tree/master/examples/bootstrap&quot;) See sources\n</code></pre>\n</li>\n<li>\n<pre><code>.container\n</code></pre>\n</li>\n<li>\n<pre><code>  div(sg-content)\n</code></pre>\n</li>\n</ul>\n<p>*/</p>\n<p>@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);</p>\n<p>/*</p>\n<ul>\n<li>jumbotron for the styleguide.\n*/</li>\n</ul>\n<p>.jumbotron-styleguide {\nbackground: #fafafa;\nborder-bottom: solid 1px #eee;\ntext-align: center;\nfont-family: 'Source Sans Pro', sans-serif;</p>\n<p>text-rendering: optimizeLegibility !important;\n-webkit-font-smoothing: antialiased !important;\n-moz-osx-font-smoothing: grayscale;\n}</p>\n<p>.jumbotron-styleguide h1 {\nfont-family: 'Source Sans Pro', sans-serif;\nfont-weight: 100;\ncolor: #111;\nfont-size: 3.4em;\nmargin-bottom: 20px;\n}</p>\n<p>.jumbotron-styleguide p {\nfont-weight: 400;\nfont-size: 1.15em;\nline-height: 1.7;\ncolor: #222;\n}</p>\n<p>.jumbotron-styleguide .btn {\nfont-family: 'Source Sans Pro', sans-serif;\ntext-transform: uppercase;\nfont-weight: bold;\nfont-size: 0.8em;\nletter-spacing: 1px;\npadding: 10px 30px;\nmargin: 10px 5px 0 5px;\ncolor: #1a8;\nborder-color: #ddd;\n}</p>\n<p>.jumbotron-styleguide .btn:hover {\nbackground: #1a8;\nborder-color: transparent;\ncolor: #fff;\n}</p>\n<p>.jumbotron-styleguide .container {\nmax-width: 500px;\n}</p>\n<p>/*</p>\n<ul>\n<li>override heading styles.\n*/</li>\n</ul>\n<p>h2.sg.sg {\nfont-family: 'Source Sans Pro', sans-serif;\nfont-weight: 300;\nfont-size: 3em;\n}</p>\n<p>/*</p>\n<ul>\n<li>for @example.slim\n*/</li>\n</ul>\n<p>.sg-slim .sg-canvas {\nmax-width: 300px;\n}</p>\n<p>/*</p>\n<ul>\n<li>for @example.wide\n*/</li>\n</ul>\n<p>.sg-wide .sg-canvas {\nmax-width: 540px;\n}</p>"
            }
          }
        }
      }
    }
  }
}
`

I am using Node 6.3.0 on OSX 10.11

Can you assist ?

Michał

**Comment by rstacruz** [comment]
you seem to be using styledown v2-pre. use the 1.x versions.

**Comment by padsbanger** [comment]
Thank you for response. 

As you said, I managed to solve this problem by `npm install -g styledown@1.2`
