### ISSUE TITLE
Styledown: Command Not Found

### ISSUE THREAD

**Issue by erwstout** [styledown/styledown#26]
I noticed that this tool hasn't been updated in some time so I'm wondering if its now abandoned, but while trying to test out styledown I get a `command not found` error in the terminal.

It might be safe to assume this is failing because of newer versions of node. Even running `styledown --help` returns `command not found`.

Node version: `6.4.0`
npm version: `3.10.3`
Running on Mac OSX `10.11.6`

Any thoughts?

**Comment by HectorPersonalGit** [comment]
Having the same issue.

**Comment by stephanie** [comment]
Having the same issue!

**Comment by stephanie** [comment]
Using this for the moment, but it'd be great to use your original: https://www.versioneye.com/nodejs/styledown-redux/1.0.3

**Comment by erwstout** [comment]
Just wanted to say thanks for pointing me to this version @stephs829  it's working great!

**Comment by josephrexme** [comment]
It is an issue with node >= 6.0 and I believe it may have to do with the jade dependency that should now be pug

**Comment by erwstout** [comment]
Possibly, I have a few other packages that use the jade dep and I get a warning but doesn't fully fail. I believe it's more on the node side.

**Comment by sanbor** [comment]
The global installation it is not working on Ubuntu 16.04. If I install it without `--global` I can run the executable by executing `./node_modules/styledown/bin/styledown`.
